server:
  port: 8081
spring:
  application:
       name: publicconfigserver
  cloud:
     config:
       server:
          git:
            uri: http://gitlab.99bicycle.com/tonghengzhen/config-server.git
            username: tonghengzhen
            password: thz010203

eureka:
  client:
    service-url:
       defaultZone: http://106.15.47.133:10000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

# spring boot 监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
