spring:
  datasource:
    url: jdbc:mysql://139.196.194.172:3306/electric_bicycle_pro_test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=true
    userName: jjtest
    password: 99b39189a35c
    driver-class-name: com.mysql.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-idle: 10


# LOGGING
logging:
    level:
       com.example: DEBUG
#    config: classpath:logback/logback-dev.xml
    config: classpath:logback/logback-logstash.xml