server:
  port: 8080


spring:
  freemarker:
    prefer-file-system-access: false
  application:
       name: demo2
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
  profiles:
#    active: local
    active: dev
#    active: prod
  http:
    encoding:
      charset: utf-8
      enabled: true #是否开启http的编码支持
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
  aop:
      proxy-target-class: true
  jmx:
    default-domain: demo2

# spring boot 监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
